version = 0.1

[default.global.parameters]
region = "us-east-1"

[default.build.parameters]
beta_features = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
profile = "plock-admin"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nwao0jggejqu"
stack_name = "aws-messaging-webhook-dev"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
disable_rollback = true
parameter_overrides = "pStage=dev pHostedZoneId=Z16D1PNQBSPVGS pMailDomain=mail.bigkong.com pMailInbox=hello pApiKeysParameterName=/messaging-webhook/dev/api-keys"
