version = 0.1

[default.global.parameters]
region = "us-east-1"

[default.build.parameters]
beta_features = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
profile = "shared-admin"
resolve_s3 = true
#s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nwao0jggejqu"
stack_name = "smoketurner-inbox-prod"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
disable_rollback = true
parameter_overrides = "pStage=prod pHostedZoneId=Z09504702V4HQRPZLSGQ pMailDomain=inbox.smoketurner.com pMailInbox=hello pApiKeysParameterName=/messaging-webhook/prod/api-keys pMailTrackingDomain=click.inbox.smoketurner.com"
